### PR TITLE
Remove section that disallows using shorthand operators

### PR DESCRIPTION
**Pull request by amiel**
In our discussion, we all agreed that we like being able to use `++` and `+= ...`.

### CODE REVIEW

**Comment by amiel** [comment]
@timwhite47 do you know if there is a rule in the `.eslintrc` that reflects this rule?

**Comment by timwhite47** [comment]
@amiel http://eslint.org/docs/rules/no-plusplus

**Comment by amiel** [comment]
Thanks @timwhite47, I think that did the trick.

**Comment by nathancarnes** [comment]
This looks good to me, anyone else have objections?

**Comment by timwhite47** [comment]
@nathancarnes LGTM

**Pull request merged**
