### PR TITLE
Change if whitespace style to include a space

### PR DESCRIPTION
**Pull request by amiel**
There was some disagreement about this one in our discussion.

I realize I may be outvoted on here, but I thought I would start the pull-request as a place to vote/discuss preferences on whitespace after `if`.

Since many of the examples contain `if` statements, this pull-request contains a lot of changes other than the actual rule. The actual rule change can be found here: 0a617a2c89b0ff11024401820ddf3deb7242390b.

### CODE REVIEW

**Comment by nathancarnes** [comment]
@amiel given that this is purely a style preference, do you have any ideas on how to reach a decision here?

I don't have a preference here, other than for consistency.

**Comment by timwhite47** [comment]
Given this is a style convention from the old style guide, I'm okay standing aside on the space after `if`.

**Comment by nathancarnes** [comment]
@timwhite47 that's a really great point. Continuity with the previous style guide seems like a pretty good tie-breaker to me.

**Comment by andreafrost** [comment]
For what it's worth, I prefer having a space after `if`.  I'm also totally fine adopting whatever the group decides.

**Comment by amiel** [comment]
I prefer the space as well, but mostly would like to go with what most people would be happy with.

**Comment by nathancarnes** [comment]
Okay, I'd like to propose we merge this. It doesn't sound like anyone felt strongly about _not_ doing it, a few folks prefer it, and it maintains continuity with our previous style guide.

Does that work for everyone?

**Pull request merged**
